// Copyright 2017-2018 Espressif Systems (Shanghai) PTE LTD
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#ifndef _SOC_CORE0_INTERRUPT_REG_H_
#define _SOC_CORE0_INTERRUPT_REG_H_


#ifdef __cplusplus
extern "C" {
#endif
#include "periph_addr.h"

#define CORE0_INTERRUPT_LP_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x0)
/* CORE0_INTERRUPT_LP_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_LP_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_LP_INT_MAP_M  ((CORE0_INTERRUPT_LP_INT_MAP_V)<<(CORE0_INTERRUPT_LP_INT_MAP_S))
#define CORE0_INTERRUPT_LP_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_LP_INT_MAP_S  0

#define CORE0_INTERRUPT_CPU_ICM_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x4)
/* CORE0_INTERRUPT_CPU_ICM_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_ICM_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CPU_ICM_INT_MAP_M  ((CORE0_INTERRUPT_CPU_ICM_INT_MAP_V)<<(CORE0_INTERRUPT_CPU_ICM_INT_MAP_S))
#define CORE0_INTERRUPT_CPU_ICM_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CPU_ICM_INT_MAP_S  0

#define CORE0_INTERRUPT_SYS_ICM_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x8)
/* CORE0_INTERRUPT_SYS_ICM_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYS_ICM_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYS_ICM_INT_MAP_M  ((CORE0_INTERRUPT_SYS_ICM_INT_MAP_V)<<(CORE0_INTERRUPT_SYS_ICM_INT_MAP_S))
#define CORE0_INTERRUPT_SYS_ICM_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYS_ICM_INT_MAP_S  0

#define CORE0_INTERRUPT_USB_DEVICE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xC)
/* CORE0_INTERRUPT_USB_DEVICE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_USB_DEVICE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_USB_DEVICE_INT_MAP_M  ((CORE0_INTERRUPT_USB_DEVICE_INT_MAP_V)<<(CORE0_INTERRUPT_USB_DEVICE_INT_MAP_S))
#define CORE0_INTERRUPT_USB_DEVICE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_USB_DEVICE_INT_MAP_S  0

#define CORE0_INTERRUPT_SDIO_HOST_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x10)
/* CORE0_INTERRUPT_SDIO_HOST_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SDIO_HOST_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SDIO_HOST_INT_MAP_M  ((CORE0_INTERRUPT_SDIO_HOST_INT_MAP_V)<<(CORE0_INTERRUPT_SDIO_HOST_INT_MAP_S))
#define CORE0_INTERRUPT_SDIO_HOST_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SDIO_HOST_INT_MAP_S  0

#define CORE0_INTERRUPT_GDMA_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x14)
/* CORE0_INTERRUPT_GDMA_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_GDMA_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_GDMA_INT_MAP_M  ((CORE0_INTERRUPT_GDMA_INT_MAP_V)<<(CORE0_INTERRUPT_GDMA_INT_MAP_S))
#define CORE0_INTERRUPT_GDMA_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_GDMA_INT_MAP_S  0

#define CORE0_INTERRUPT_SPI_INT_2_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x18)
/* CORE0_INTERRUPT_SPI_INT_2_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SPI_INT_2_MAP    0x0000001F
#define CORE0_INTERRUPT_SPI_INT_2_MAP_M  ((CORE0_INTERRUPT_SPI_INT_2_MAP_V)<<(CORE0_INTERRUPT_SPI_INT_2_MAP_S))
#define CORE0_INTERRUPT_SPI_INT_2_MAP_V  0x1F
#define CORE0_INTERRUPT_SPI_INT_2_MAP_S  0

#define CORE0_INTERRUPT_SPI_INT_3_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1C)
/* CORE0_INTERRUPT_SPI_INT_3_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SPI_INT_3_MAP    0x0000001F
#define CORE0_INTERRUPT_SPI_INT_3_MAP_M  ((CORE0_INTERRUPT_SPI_INT_3_MAP_V)<<(CORE0_INTERRUPT_SPI_INT_3_MAP_S))
#define CORE0_INTERRUPT_SPI_INT_3_MAP_V  0x1F
#define CORE0_INTERRUPT_SPI_INT_3_MAP_S  0

#define CORE0_INTERRUPT_I2S0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x20)
/* CORE0_INTERRUPT_I2S0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I2S0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I2S0_INT_MAP_M  ((CORE0_INTERRUPT_I2S0_INT_MAP_V)<<(CORE0_INTERRUPT_I2S0_INT_MAP_S))
#define CORE0_INTERRUPT_I2S0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I2S0_INT_MAP_S  0

#define CORE0_INTERRUPT_I2S1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x24)
/* CORE0_INTERRUPT_I2S1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I2S1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I2S1_INT_MAP_M  ((CORE0_INTERRUPT_I2S1_INT_MAP_V)<<(CORE0_INTERRUPT_I2S1_INT_MAP_S))
#define CORE0_INTERRUPT_I2S1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I2S1_INT_MAP_S  0

#define CORE0_INTERRUPT_I2S2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x28)
/* CORE0_INTERRUPT_I2S2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I2S2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I2S2_INT_MAP_M  ((CORE0_INTERRUPT_I2S2_INT_MAP_V)<<(CORE0_INTERRUPT_I2S2_INT_MAP_S))
#define CORE0_INTERRUPT_I2S2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I2S2_INT_MAP_S  0

#define CORE0_INTERRUPT_UHCI0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x2C)
/* CORE0_INTERRUPT_UHCI0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_UHCI0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_UHCI0_INT_MAP_M  ((CORE0_INTERRUPT_UHCI0_INT_MAP_V)<<(CORE0_INTERRUPT_UHCI0_INT_MAP_S))
#define CORE0_INTERRUPT_UHCI0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_UHCI0_INT_MAP_S  0

#define CORE0_INTERRUPT_UART0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x30)
/* CORE0_INTERRUPT_UART0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_UART0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_UART0_INT_MAP_M  ((CORE0_INTERRUPT_UART0_INT_MAP_V)<<(CORE0_INTERRUPT_UART0_INT_MAP_S))
#define CORE0_INTERRUPT_UART0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_UART0_INT_MAP_S  0

#define CORE0_INTERRUPT_UART1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x34)
/* CORE0_INTERRUPT_UART1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_UART1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_UART1_INT_MAP_M  ((CORE0_INTERRUPT_UART1_INT_MAP_V)<<(CORE0_INTERRUPT_UART1_INT_MAP_S))
#define CORE0_INTERRUPT_UART1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_UART1_INT_MAP_S  0

#define CORE0_INTERRUPT_UART2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x38)
/* CORE0_INTERRUPT_UART2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_UART2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_UART2_INT_MAP_M  ((CORE0_INTERRUPT_UART2_INT_MAP_V)<<(CORE0_INTERRUPT_UART2_INT_MAP_S))
#define CORE0_INTERRUPT_UART2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_UART2_INT_MAP_S  0

#define CORE0_INTERRUPT_UART3_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x3C)
/* CORE0_INTERRUPT_UART3_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_UART3_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_UART3_INT_MAP_M  ((CORE0_INTERRUPT_UART3_INT_MAP_V)<<(CORE0_INTERRUPT_UART3_INT_MAP_S))
#define CORE0_INTERRUPT_UART3_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_UART3_INT_MAP_S  0

#define CORE0_INTERRUPT_UART4_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x40)
/* CORE0_INTERRUPT_UART4_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_UART4_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_UART4_INT_MAP_M  ((CORE0_INTERRUPT_UART4_INT_MAP_V)<<(CORE0_INTERRUPT_UART4_INT_MAP_S))
#define CORE0_INTERRUPT_UART4_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_UART4_INT_MAP_S  0

#define CORE0_INTERRUPT_LCD_CAM_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x44)
/* CORE0_INTERRUPT_LCD_CAM_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_LCD_CAM_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_LCD_CAM_INT_MAP_M  ((CORE0_INTERRUPT_LCD_CAM_INT_MAP_V)<<(CORE0_INTERRUPT_LCD_CAM_INT_MAP_S))
#define CORE0_INTERRUPT_LCD_CAM_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_LCD_CAM_INT_MAP_S  0

#define CORE0_INTERRUPT_APB_ADC_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x48)
/* CORE0_INTERRUPT_APB_ADC_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_APB_ADC_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_APB_ADC_INT_MAP_M  ((CORE0_INTERRUPT_APB_ADC_INT_MAP_V)<<(CORE0_INTERRUPT_APB_ADC_INT_MAP_S))
#define CORE0_INTERRUPT_APB_ADC_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_APB_ADC_INT_MAP_S  0

#define CORE0_INTERRUPT_PWM0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x4C)
/* CORE0_INTERRUPT_PWM0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_PWM0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_PWM0_INT_MAP_M  ((CORE0_INTERRUPT_PWM0_INT_MAP_V)<<(CORE0_INTERRUPT_PWM0_INT_MAP_S))
#define CORE0_INTERRUPT_PWM0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_PWM0_INT_MAP_S  0

#define CORE0_INTERRUPT_PWM1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x50)
/* CORE0_INTERRUPT_PWM1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_PWM1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_PWM1_INT_MAP_M  ((CORE0_INTERRUPT_PWM1_INT_MAP_V)<<(CORE0_INTERRUPT_PWM1_INT_MAP_S))
#define CORE0_INTERRUPT_PWM1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_PWM1_INT_MAP_S  0

#define CORE0_INTERRUPT_CAN0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x54)
/* CORE0_INTERRUPT_CAN0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CAN0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CAN0_INT_MAP_M  ((CORE0_INTERRUPT_CAN0_INT_MAP_V)<<(CORE0_INTERRUPT_CAN0_INT_MAP_S))
#define CORE0_INTERRUPT_CAN0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CAN0_INT_MAP_S  0

#define CORE0_INTERRUPT_CAN1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x58)
/* CORE0_INTERRUPT_CAN1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CAN1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CAN1_INT_MAP_M  ((CORE0_INTERRUPT_CAN1_INT_MAP_V)<<(CORE0_INTERRUPT_CAN1_INT_MAP_S))
#define CORE0_INTERRUPT_CAN1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CAN1_INT_MAP_S  0

#define CORE0_INTERRUPT_CAN2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x5C)
/* CORE0_INTERRUPT_CAN2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CAN2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CAN2_INT_MAP_M  ((CORE0_INTERRUPT_CAN2_INT_MAP_V)<<(CORE0_INTERRUPT_CAN2_INT_MAP_S))
#define CORE0_INTERRUPT_CAN2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CAN2_INT_MAP_S  0

#define CORE0_INTERRUPT_RMT_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x60)
/* CORE0_INTERRUPT_RMT_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_RMT_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_RMT_INT_MAP_M  ((CORE0_INTERRUPT_RMT_INT_MAP_V)<<(CORE0_INTERRUPT_RMT_INT_MAP_S))
#define CORE0_INTERRUPT_RMT_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_RMT_INT_MAP_S  0

#define CORE0_INTERRUPT_I2C_EXT0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x64)
/* CORE0_INTERRUPT_I2C_EXT0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I2C_EXT0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I2C_EXT0_INT_MAP_M  ((CORE0_INTERRUPT_I2C_EXT0_INT_MAP_V)<<(CORE0_INTERRUPT_I2C_EXT0_INT_MAP_S))
#define CORE0_INTERRUPT_I2C_EXT0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I2C_EXT0_INT_MAP_S  0

#define CORE0_INTERRUPT_I2C_EXT1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x68)
/* CORE0_INTERRUPT_I2C_EXT1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I2C_EXT1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I2C_EXT1_INT_MAP_M  ((CORE0_INTERRUPT_I2C_EXT1_INT_MAP_V)<<(CORE0_INTERRUPT_I2C_EXT1_INT_MAP_S))
#define CORE0_INTERRUPT_I2C_EXT1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I2C_EXT1_INT_MAP_S  0

#define CORE0_INTERRUPT_TIMER_INT1_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x6C)
/* CORE0_INTERRUPT_TIMER_INT1_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TIMER_INT1_MAP    0x0000001F
#define CORE0_INTERRUPT_TIMER_INT1_MAP_M  ((CORE0_INTERRUPT_TIMER_INT1_MAP_V)<<(CORE0_INTERRUPT_TIMER_INT1_MAP_S))
#define CORE0_INTERRUPT_TIMER_INT1_MAP_V  0x1F
#define CORE0_INTERRUPT_TIMER_INT1_MAP_S  0

#define CORE0_INTERRUPT_TIMER_INT2_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x70)
/* CORE0_INTERRUPT_TIMER_INT2_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TIMER_INT2_MAP    0x0000001F
#define CORE0_INTERRUPT_TIMER_INT2_MAP_M  ((CORE0_INTERRUPT_TIMER_INT2_MAP_V)<<(CORE0_INTERRUPT_TIMER_INT2_MAP_S))
#define CORE0_INTERRUPT_TIMER_INT2_MAP_V  0x1F
#define CORE0_INTERRUPT_TIMER_INT2_MAP_S  0

#define CORE0_INTERRUPT_TG0_T0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x74)
/* CORE0_INTERRUPT_TG0_T0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG0_T0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG0_T0_INT_MAP_M  ((CORE0_INTERRUPT_TG0_T0_INT_MAP_V)<<(CORE0_INTERRUPT_TG0_T0_INT_MAP_S))
#define CORE0_INTERRUPT_TG0_T0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG0_T0_INT_MAP_S  0

#define CORE0_INTERRUPT_TG0_T1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x78)
/* CORE0_INTERRUPT_TG0_T1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG0_T1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG0_T1_INT_MAP_M  ((CORE0_INTERRUPT_TG0_T1_INT_MAP_V)<<(CORE0_INTERRUPT_TG0_T1_INT_MAP_S))
#define CORE0_INTERRUPT_TG0_T1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG0_T1_INT_MAP_S  0

#define CORE0_INTERRUPT_TG0_WDT_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x7C)
/* CORE0_INTERRUPT_TG0_WDT_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG0_WDT_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG0_WDT_INT_MAP_M  ((CORE0_INTERRUPT_TG0_WDT_INT_MAP_V)<<(CORE0_INTERRUPT_TG0_WDT_INT_MAP_S))
#define CORE0_INTERRUPT_TG0_WDT_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG0_WDT_INT_MAP_S  0

#define CORE0_INTERRUPT_TG1_T0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x80)
/* CORE0_INTERRUPT_TG1_T0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG1_T0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG1_T0_INT_MAP_M  ((CORE0_INTERRUPT_TG1_T0_INT_MAP_V)<<(CORE0_INTERRUPT_TG1_T0_INT_MAP_S))
#define CORE0_INTERRUPT_TG1_T0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG1_T0_INT_MAP_S  0

#define CORE0_INTERRUPT_TG1_T1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x84)
/* CORE0_INTERRUPT_TG1_T1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG1_T1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG1_T1_INT_MAP_M  ((CORE0_INTERRUPT_TG1_T1_INT_MAP_V)<<(CORE0_INTERRUPT_TG1_T1_INT_MAP_S))
#define CORE0_INTERRUPT_TG1_T1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG1_T1_INT_MAP_S  0

#define CORE0_INTERRUPT_TG1_WDT_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x88)
/* CORE0_INTERRUPT_TG1_WDT_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG1_WDT_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG1_WDT_INT_MAP_M  ((CORE0_INTERRUPT_TG1_WDT_INT_MAP_V)<<(CORE0_INTERRUPT_TG1_WDT_INT_MAP_S))
#define CORE0_INTERRUPT_TG1_WDT_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG1_WDT_INT_MAP_S  0

#define CORE0_INTERRUPT_TG2_T0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x8C)
/* CORE0_INTERRUPT_TG2_T0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG2_T0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG2_T0_INT_MAP_M  ((CORE0_INTERRUPT_TG2_T0_INT_MAP_V)<<(CORE0_INTERRUPT_TG2_T0_INT_MAP_S))
#define CORE0_INTERRUPT_TG2_T0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG2_T0_INT_MAP_S  0

#define CORE0_INTERRUPT_TG2_T1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x90)
/* CORE0_INTERRUPT_TG2_T1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG2_T1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG2_T1_INT_MAP_M  ((CORE0_INTERRUPT_TG2_T1_INT_MAP_V)<<(CORE0_INTERRUPT_TG2_T1_INT_MAP_S))
#define CORE0_INTERRUPT_TG2_T1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG2_T1_INT_MAP_S  0

#define CORE0_INTERRUPT_TG2_WDT_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x94)
/* CORE0_INTERRUPT_TG2_WDT_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG2_WDT_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG2_WDT_INT_MAP_M  ((CORE0_INTERRUPT_TG2_WDT_INT_MAP_V)<<(CORE0_INTERRUPT_TG2_WDT_INT_MAP_S))
#define CORE0_INTERRUPT_TG2_WDT_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG2_WDT_INT_MAP_S  0

#define CORE0_INTERRUPT_TG3_T0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x98)
/* CORE0_INTERRUPT_TG3_T0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG3_T0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG3_T0_INT_MAP_M  ((CORE0_INTERRUPT_TG3_T0_INT_MAP_V)<<(CORE0_INTERRUPT_TG3_T0_INT_MAP_S))
#define CORE0_INTERRUPT_TG3_T0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG3_T0_INT_MAP_S  0

#define CORE0_INTERRUPT_TG3_T1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x9C)
/* CORE0_INTERRUPT_TG3_T1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG3_T1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG3_T1_INT_MAP_M  ((CORE0_INTERRUPT_TG3_T1_INT_MAP_V)<<(CORE0_INTERRUPT_TG3_T1_INT_MAP_S))
#define CORE0_INTERRUPT_TG3_T1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG3_T1_INT_MAP_S  0

#define CORE0_INTERRUPT_TG3_WDT_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xA0)
/* CORE0_INTERRUPT_TG3_WDT_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_TG3_WDT_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_TG3_WDT_INT_MAP_M  ((CORE0_INTERRUPT_TG3_WDT_INT_MAP_V)<<(CORE0_INTERRUPT_TG3_WDT_INT_MAP_S))
#define CORE0_INTERRUPT_TG3_WDT_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_TG3_WDT_INT_MAP_S  0

#define CORE0_INTERRUPT_LEDC_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xA4)
/* CORE0_INTERRUPT_LEDC_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_LEDC_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_LEDC_INT_MAP_M  ((CORE0_INTERRUPT_LEDC_INT_MAP_V)<<(CORE0_INTERRUPT_LEDC_INT_MAP_S))
#define CORE0_INTERRUPT_LEDC_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_LEDC_INT_MAP_S  0

#define CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xA8)
/* CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP_M  ((CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP_V)<<(CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP_S))
#define CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYSTIMER0_TARGET0_INT_MAP_S  0

#define CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xAC)
/* CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP_M  ((CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP_V)<<(CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP_S))
#define CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYSTIMER0_TARGET1_INT_MAP_S  0

#define CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xB0)
/* CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP_M  ((CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP_V)<<(CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP_S))
#define CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYSTIMER0_TARGET2_INT_MAP_S  0

#define CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xB4)
/* CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP_M  ((CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP_V)<<(CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP_S))
#define CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYSTIMER1_TARGET0_INT_MAP_S  0

#define CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xB8)
/* CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP_M  ((CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP_V)<<(CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP_S))
#define CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYSTIMER1_TARGET1_INT_MAP_S  0

#define CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xBC)
/* CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP_M  ((CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP_V)<<(CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP_S))
#define CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SYSTIMER1_TARGET2_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xC0)
/* CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP_M  ((CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_IN_CH0_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xC4)
/* CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP_M  ((CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_IN_CH1_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xC8)
/* CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP_M  ((CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_IN_CH2_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xCC)
/* CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP_M  ((CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_IN_CH3_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xD0)
/* CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP_M  ((CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_IN_CH4_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xD4)
/* CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP_M  ((CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_OUT_CH0_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xD8)
/* CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP_M  ((CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_OUT_CH1_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xDC)
/* CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP_M  ((CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_OUT_CH2_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xE0)
/* CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP_M  ((CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_OUT_CH3_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xE4)
/* CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP_M  ((CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP_V)<<(CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP_S))
#define CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA_OUT_CH4_INT_MAP_S  0

#define CORE0_INTERRUPT_RSA_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xE8)
/* CORE0_INTERRUPT_RSA_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_RSA_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_RSA_INT_MAP_M  ((CORE0_INTERRUPT_RSA_INT_MAP_V)<<(CORE0_INTERRUPT_RSA_INT_MAP_S))
#define CORE0_INTERRUPT_RSA_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_RSA_INT_MAP_S  0

#define CORE0_INTERRUPT_AES_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xEC)
/* CORE0_INTERRUPT_AES_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_AES_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_AES_INT_MAP_M  ((CORE0_INTERRUPT_AES_INT_MAP_V)<<(CORE0_INTERRUPT_AES_INT_MAP_S))
#define CORE0_INTERRUPT_AES_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_AES_INT_MAP_S  0

#define CORE0_INTERRUPT_SHA_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xF0)
/* CORE0_INTERRUPT_SHA_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SHA_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SHA_INT_MAP_M  ((CORE0_INTERRUPT_SHA_INT_MAP_V)<<(CORE0_INTERRUPT_SHA_INT_MAP_S))
#define CORE0_INTERRUPT_SHA_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SHA_INT_MAP_S  0

#define CORE0_INTERRUPT_ECC_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xF4)
/* CORE0_INTERRUPT_ECC_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_ECC_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_ECC_INT_MAP_M  ((CORE0_INTERRUPT_ECC_INT_MAP_V)<<(CORE0_INTERRUPT_ECC_INT_MAP_S))
#define CORE0_INTERRUPT_ECC_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_ECC_INT_MAP_S  0

#define CORE0_INTERRUPT_GPIO_INTR0_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xF8)
/* CORE0_INTERRUPT_GPIO_INTR0_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_GPIO_INTR0_MAP    0x0000001F
#define CORE0_INTERRUPT_GPIO_INTR0_MAP_M  ((CORE0_INTERRUPT_GPIO_INTR0_MAP_V)<<(CORE0_INTERRUPT_GPIO_INTR0_MAP_S))
#define CORE0_INTERRUPT_GPIO_INTR0_MAP_V  0x1F
#define CORE0_INTERRUPT_GPIO_INTR0_MAP_S  0

#define CORE0_INTERRUPT_GPIO_INTR1_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0xFC)
/* CORE0_INTERRUPT_GPIO_INTR1_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_GPIO_INTR1_MAP    0x0000001F
#define CORE0_INTERRUPT_GPIO_INTR1_MAP_M  ((CORE0_INTERRUPT_GPIO_INTR1_MAP_V)<<(CORE0_INTERRUPT_GPIO_INTR1_MAP_S))
#define CORE0_INTERRUPT_GPIO_INTR1_MAP_V  0x1F
#define CORE0_INTERRUPT_GPIO_INTR1_MAP_S  0

#define CORE0_INTERRUPT_GPIO_INTR2_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x100)
/* CORE0_INTERRUPT_GPIO_INTR2_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_GPIO_INTR2_MAP    0x0000001F
#define CORE0_INTERRUPT_GPIO_INTR2_MAP_M  ((CORE0_INTERRUPT_GPIO_INTR2_MAP_V)<<(CORE0_INTERRUPT_GPIO_INTR2_MAP_S))
#define CORE0_INTERRUPT_GPIO_INTR2_MAP_V  0x1F
#define CORE0_INTERRUPT_GPIO_INTR2_MAP_S  0

#define CORE0_INTERRUPT_GPIO_INTR3_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x104)
/* CORE0_INTERRUPT_GPIO_INTR3_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_GPIO_INTR3_MAP    0x0000001F
#define CORE0_INTERRUPT_GPIO_INTR3_MAP_M  ((CORE0_INTERRUPT_GPIO_INTR3_MAP_V)<<(CORE0_INTERRUPT_GPIO_INTR3_MAP_S))
#define CORE0_INTERRUPT_GPIO_INTR3_MAP_V  0x1F
#define CORE0_INTERRUPT_GPIO_INTR3_MAP_S  0

#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x108)
/* CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP    0x0000001F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP_M  ((CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP_V)<<(CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP_S))
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP_V  0x1F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_0_MAP_S  0

#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x10C)
/* CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP    0x0000001F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP_M  ((CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP_V)<<(CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP_S))
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP_V  0x1F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_1_MAP_S  0

#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x110)
/* CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP    0x0000001F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP_M  ((CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP_V)<<(CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP_S))
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP_V  0x1F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_2_MAP_S  0

#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x114)
/* CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP    0x0000001F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP_M  ((CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP_V)<<(CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP_S))
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP_V  0x1F
#define CORE0_INTERRUPT_CPU_INT_FROM_CPU_3_MAP_S  0

#define CORE0_INTERRUPT_CACHE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x118)
/* CORE0_INTERRUPT_CACHE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CACHE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CACHE_INT_MAP_M  ((CORE0_INTERRUPT_CACHE_INT_MAP_V)<<(CORE0_INTERRUPT_CACHE_INT_MAP_S))
#define CORE0_INTERRUPT_CACHE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CACHE_INT_MAP_S  0

#define CORE0_INTERRUPT_MSPI_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x11C)
/* CORE0_INTERRUPT_MSPI_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_MSPI_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_MSPI_INT_MAP_M  ((CORE0_INTERRUPT_MSPI_INT_MAP_V)<<(CORE0_INTERRUPT_MSPI_INT_MAP_S))
#define CORE0_INTERRUPT_MSPI_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_MSPI_INT_MAP_S  0

#define CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x120)
/* CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP_M  ((CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP_V)<<(CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP_S))
#define CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CSI_BRIDGE_INT_MAP_S  0

#define CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x124)
/* CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP_M  ((CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP_V)<<(CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP_S))
#define CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DSI_BRIDGE_INT_MAP_S  0

#define CORE0_INTERRUPT_CSI_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x128)
/* CORE0_INTERRUPT_CSI_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CSI_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CSI_INT_MAP_M  ((CORE0_INTERRUPT_CSI_INT_MAP_V)<<(CORE0_INTERRUPT_CSI_INT_MAP_S))
#define CORE0_INTERRUPT_CSI_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CSI_INT_MAP_S  0

#define CORE0_INTERRUPT_DSI_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x12C)
/* CORE0_INTERRUPT_DSI_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DSI_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DSI_INT_MAP_M  ((CORE0_INTERRUPT_DSI_INT_MAP_V)<<(CORE0_INTERRUPT_DSI_INT_MAP_S))
#define CORE0_INTERRUPT_DSI_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DSI_INT_MAP_S  0

#define CORE0_INTERRUPT_GMII_PHY_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x130)
/* CORE0_INTERRUPT_GMII_PHY_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_GMII_PHY_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_GMII_PHY_INT_MAP_M  ((CORE0_INTERRUPT_GMII_PHY_INT_MAP_V)<<(CORE0_INTERRUPT_GMII_PHY_INT_MAP_S))
#define CORE0_INTERRUPT_GMII_PHY_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_GMII_PHY_INT_MAP_S  0

#define CORE0_INTERRUPT_LPI_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x134)
/* CORE0_INTERRUPT_LPI_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_LPI_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_LPI_INT_MAP_M  ((CORE0_INTERRUPT_LPI_INT_MAP_V)<<(CORE0_INTERRUPT_LPI_INT_MAP_S))
#define CORE0_INTERRUPT_LPI_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_LPI_INT_MAP_S  0

#define CORE0_INTERRUPT_PMT_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x138)
/* CORE0_INTERRUPT_PMT_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_PMT_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_PMT_INT_MAP_M  ((CORE0_INTERRUPT_PMT_INT_MAP_V)<<(CORE0_INTERRUPT_PMT_INT_MAP_S))
#define CORE0_INTERRUPT_PMT_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_PMT_INT_MAP_S  0

#define CORE0_INTERRUPT_REVMII_PHY_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x13C)
/* CORE0_INTERRUPT_REVMII_PHY_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_REVMII_PHY_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_REVMII_PHY_INT_MAP_M  ((CORE0_INTERRUPT_REVMII_PHY_INT_MAP_V)<<(CORE0_INTERRUPT_REVMII_PHY_INT_MAP_S))
#define CORE0_INTERRUPT_REVMII_PHY_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_REVMII_PHY_INT_MAP_S  0

#define CORE0_INTERRUPT_SBD_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x140)
/* CORE0_INTERRUPT_SBD_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SBD_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SBD_INT_MAP_M  ((CORE0_INTERRUPT_SBD_INT_MAP_V)<<(CORE0_INTERRUPT_SBD_INT_MAP_S))
#define CORE0_INTERRUPT_SBD_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SBD_INT_MAP_S  0

#define CORE0_INTERRUPT_USB_OTG_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x144)
/* CORE0_INTERRUPT_USB_OTG_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_USB_OTG_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_USB_OTG_INT_MAP_M  ((CORE0_INTERRUPT_USB_OTG_INT_MAP_V)<<(CORE0_INTERRUPT_USB_OTG_INT_MAP_S))
#define CORE0_INTERRUPT_USB_OTG_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_USB_OTG_INT_MAP_S  0

#define CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x148)
/* CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP_M  ((CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP_V)<<(CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP_S))
#define CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_USB_OTG_ENDP_MULTI_PROC_INT_MAP_S  0

#define CORE0_INTERRUPT_JPEG_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x14C)
/* CORE0_INTERRUPT_JPEG_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_JPEG_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_JPEG_INT_MAP_M  ((CORE0_INTERRUPT_JPEG_INT_MAP_V)<<(CORE0_INTERRUPT_JPEG_INT_MAP_S))
#define CORE0_INTERRUPT_JPEG_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_JPEG_INT_MAP_S  0

#define CORE0_INTERRUPT_PPA_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x150)
/* CORE0_INTERRUPT_PPA_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_PPA_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_PPA_INT_MAP_M  ((CORE0_INTERRUPT_PPA_INT_MAP_V)<<(CORE0_INTERRUPT_PPA_INT_MAP_S))
#define CORE0_INTERRUPT_PPA_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_PPA_INT_MAP_S  0

#define CORE0_INTERRUPT_CORE0_TRACE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x154)
/* CORE0_INTERRUPT_CORE0_TRACE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CORE0_TRACE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CORE0_TRACE_INT_MAP_M  ((CORE0_INTERRUPT_CORE0_TRACE_INT_MAP_V)<<(CORE0_INTERRUPT_CORE0_TRACE_INT_MAP_S))
#define CORE0_INTERRUPT_CORE0_TRACE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CORE0_TRACE_INT_MAP_S  0

#define CORE0_INTERRUPT_CORE1_TRACE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x158)
/* CORE0_INTERRUPT_CORE1_TRACE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CORE1_TRACE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CORE1_TRACE_INT_MAP_M  ((CORE0_INTERRUPT_CORE1_TRACE_INT_MAP_V)<<(CORE0_INTERRUPT_CORE1_TRACE_INT_MAP_S))
#define CORE0_INTERRUPT_CORE1_TRACE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CORE1_TRACE_INT_MAP_S  0

#define CORE0_INTERRUPT_CORE2_TRACE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x15C)
/* CORE0_INTERRUPT_CORE2_TRACE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CORE2_TRACE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CORE2_TRACE_INT_MAP_M  ((CORE0_INTERRUPT_CORE2_TRACE_INT_MAP_V)<<(CORE0_INTERRUPT_CORE2_TRACE_INT_MAP_S))
#define CORE0_INTERRUPT_CORE2_TRACE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CORE2_TRACE_INT_MAP_S  0

#define CORE0_INTERRUPT_CORE3_TRACE_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x160)
/* CORE0_INTERRUPT_CORE3_TRACE_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CORE3_TRACE_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_CORE3_TRACE_INT_MAP_M  ((CORE0_INTERRUPT_CORE3_TRACE_INT_MAP_V)<<(CORE0_INTERRUPT_CORE3_TRACE_INT_MAP_S))
#define CORE0_INTERRUPT_CORE3_TRACE_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_CORE3_TRACE_INT_MAP_S  0

#define CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x164)
/* CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP_M  ((CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP_V)<<(CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP_S))
#define CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_HP_CORE_CTRL_INT_MAP_S  0

#define CORE0_INTERRUPT_ISP_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x168)
/* CORE0_INTERRUPT_ISP_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_ISP_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_ISP_INT_MAP_M  ((CORE0_INTERRUPT_ISP_INT_MAP_V)<<(CORE0_INTERRUPT_ISP_INT_MAP_S))
#define CORE0_INTERRUPT_ISP_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_ISP_INT_MAP_S  0

#define CORE0_INTERRUPT_I3C_MST_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x16C)
/* CORE0_INTERRUPT_I3C_MST_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I3C_MST_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I3C_MST_INT_MAP_M  ((CORE0_INTERRUPT_I3C_MST_INT_MAP_V)<<(CORE0_INTERRUPT_I3C_MST_INT_MAP_S))
#define CORE0_INTERRUPT_I3C_MST_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I3C_MST_INT_MAP_S  0

#define CORE0_INTERRUPT_I3C_SLV_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x170)
/* CORE0_INTERRUPT_I3C_SLV_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_I3C_SLV_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_I3C_SLV_INT_MAP_M  ((CORE0_INTERRUPT_I3C_SLV_INT_MAP_V)<<(CORE0_INTERRUPT_I3C_SLV_INT_MAP_S))
#define CORE0_INTERRUPT_I3C_SLV_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_I3C_SLV_INT_MAP_S  0

#define CORE0_INTERRUPT_USB_OTG11_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x174)
/* CORE0_INTERRUPT_USB_OTG11_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_USB_OTG11_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_USB_OTG11_INT_MAP_M  ((CORE0_INTERRUPT_USB_OTG11_INT_MAP_V)<<(CORE0_INTERRUPT_USB_OTG11_INT_MAP_S))
#define CORE0_INTERRUPT_USB_OTG11_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_USB_OTG11_INT_MAP_S  0

#define CORE0_INTERRUPT_SLC0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x178)
/* CORE0_INTERRUPT_SLC0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SLC0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SLC0_INT_MAP_M  ((CORE0_INTERRUPT_SLC0_INT_MAP_V)<<(CORE0_INTERRUPT_SLC0_INT_MAP_S))
#define CORE0_INTERRUPT_SLC0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SLC0_INT_MAP_S  0

#define CORE0_INTERRUPT_SLC1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x17C)
/* CORE0_INTERRUPT_SLC1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_SLC1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_SLC1_INT_MAP_M  ((CORE0_INTERRUPT_SLC1_INT_MAP_V)<<(CORE0_INTERRUPT_SLC1_INT_MAP_S))
#define CORE0_INTERRUPT_SLC1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_SLC1_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x180)
/* CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_IN_CH0_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x184)
/* CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_IN_CH1_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x188)
/* CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_IN_CH2_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x18C)
/* CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_IN_CH3_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x190)
/* CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_OUT_CH0_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x194)
/* CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_OUT_CH1_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x198)
/* CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_OUT_CH2_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x19C)
/* CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_OUT_CH3_INT_MAP_S  0

#define CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1A0)
/* CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP_M  ((CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP_V)<<(CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP_S))
#define CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_DMA2D_OUT_CH4_INT_MAP_S  0

#define CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1A4)
/* CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP_M  ((CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP_V)<<(CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP_S))
#define CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_MSPI_DUALRAM_INT_MAP_S  0

#define CORE0_INTERRUPT_HP_SYSREG_INT_MAP_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1A8)
/* CORE0_INTERRUPT_HP_SYSREG_INT_MAP : R/W ;bitpos:[4:0] ;default: 5'b0 ; */
/*description: .*/
#define CORE0_INTERRUPT_HP_SYSREG_INT_MAP    0x0000001F
#define CORE0_INTERRUPT_HP_SYSREG_INT_MAP_M  ((CORE0_INTERRUPT_HP_SYSREG_INT_MAP_V)<<(CORE0_INTERRUPT_HP_SYSREG_INT_MAP_S))
#define CORE0_INTERRUPT_HP_SYSREG_INT_MAP_V  0x1F
#define CORE0_INTERRUPT_HP_SYSREG_INT_MAP_S  0

#define CORE0_INTERRUPT_INTR_STATUS_REG_0_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1AC)
/* CORE0_INTERRUPT_INTR_STATUS_0 : RO ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_INTR_STATUS_0    0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_0_M  ((CORE0_INTERRUPT_INTR_STATUS_0_V)<<(CORE0_INTERRUPT_INTR_STATUS_0_S))
#define CORE0_INTERRUPT_INTR_STATUS_0_V  0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_0_S  0

#define CORE0_INTERRUPT_INTR_STATUS_REG_1_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1B0)
/* CORE0_INTERRUPT_INTR_STATUS_1 : RO ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_INTR_STATUS_1    0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_1_M  ((CORE0_INTERRUPT_INTR_STATUS_1_V)<<(CORE0_INTERRUPT_INTR_STATUS_1_S))
#define CORE0_INTERRUPT_INTR_STATUS_1_V  0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_1_S  0

#define CORE0_INTERRUPT_INTR_STATUS_REG_2_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1B4)
/* CORE0_INTERRUPT_INTR_STATUS_2 : RO ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_INTR_STATUS_2    0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_2_M  ((CORE0_INTERRUPT_INTR_STATUS_2_V)<<(CORE0_INTERRUPT_INTR_STATUS_2_S))
#define CORE0_INTERRUPT_INTR_STATUS_2_V  0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_2_S  0

#define CORE0_INTERRUPT_INTR_STATUS_REG_3_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1B8)
/* CORE0_INTERRUPT_INTR_STATUS_3 : RO ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_INTR_STATUS_3    0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_3_M  ((CORE0_INTERRUPT_INTR_STATUS_3_V)<<(CORE0_INTERRUPT_INTR_STATUS_3_S))
#define CORE0_INTERRUPT_INTR_STATUS_3_V  0xFFFFFFFF
#define CORE0_INTERRUPT_INTR_STATUS_3_S  0

#define CORE0_INTERRUPT_CLOCK_GATE_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x1BC)
/* CORE0_INTERRUPT_REG_CLK_EN : R/W ;bitpos:[0] ;default: 1'b1 ; */
/*description: .*/
#define CORE0_INTERRUPT_REG_CLK_EN    (BIT(0))
#define CORE0_INTERRUPT_REG_CLK_EN_M  (BIT(0))
#define CORE0_INTERRUPT_REG_CLK_EN_V  0x1
#define CORE0_INTERRUPT_REG_CLK_EN_S  0

#define CORE0_INTERRUPT_REG_DATE_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x3FC)
/* CORE0_INTERRUPT_REG_DATE : R/W ;bitpos:[27:0] ;default: 28'h2003020 ; */
/*description: .*/
#define CORE0_INTERRUPT_REG_DATE    0x0FFFFFFF
#define CORE0_INTERRUPT_REG_DATE_M  ((CORE0_INTERRUPT_REG_DATE_V)<<(CORE0_INTERRUPT_REG_DATE_S))
#define CORE0_INTERRUPT_REG_DATE_V  0xFFFFFFF
#define CORE0_INTERRUPT_REG_DATE_S  0

#define CORE0_INTERRUPT_INT_ENABLE_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x200)
/* CORE0_INTERRUPT_CPU_INT_ENABLE : R/W ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_ENABLE    0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_INT_ENABLE_M  ((CORE0_INTERRUPT_CPU_INT_ENABLE_V)<<(CORE0_INTERRUPT_CPU_INT_ENABLE_S))
#define CORE0_INTERRUPT_CPU_INT_ENABLE_V  0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_INT_ENABLE_S  0

#define CORE0_INTERRUPT_INT_TYPE_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x204)
/* CORE0_INTERRUPT_CPU_INT_TYPE : R/W ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_TYPE    0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_INT_TYPE_M  ((CORE0_INTERRUPT_CPU_INT_TYPE_V)<<(CORE0_INTERRUPT_CPU_INT_TYPE_S))
#define CORE0_INTERRUPT_CPU_INT_TYPE_V  0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_INT_TYPE_S  0

#define CORE0_INTERRUPT_INT_CLEAR_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x208)
/* CORE0_INTERRUPT_CPU_INT_CLEAR : R/W ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_CLEAR    0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_INT_CLEAR_M  ((CORE0_INTERRUPT_CPU_INT_CLEAR_V)<<(CORE0_INTERRUPT_CPU_INT_CLEAR_S))
#define CORE0_INTERRUPT_CPU_INT_CLEAR_V  0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_INT_CLEAR_S  0

#define CORE0_INTERRUPT_EIP_STATUS_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x20C)
/* CORE0_INTERRUPT_CPU_EIP_STATUS : RO ;bitpos:[31:0] ;default: 32'h0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_EIP_STATUS    0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_EIP_STATUS_M  ((CORE0_INTERRUPT_CPU_EIP_STATUS_V)<<(CORE0_INTERRUPT_CPU_EIP_STATUS_S))
#define CORE0_INTERRUPT_CPU_EIP_STATUS_V  0xFFFFFFFF
#define CORE0_INTERRUPT_CPU_EIP_STATUS_S  0

#define CORE0_INTERRUPT_INT0_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x210)
/* CORE0_INTERRUPT_CPU_INT0_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT0_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT0_PRI_M  ((CORE0_INTERRUPT_CPU_INT0_PRI_V)<<(CORE0_INTERRUPT_CPU_INT0_PRI_S))
#define CORE0_INTERRUPT_CPU_INT0_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT0_PRI_S  0

#define CORE0_INTERRUPT_INT1_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x214)
/* CORE0_INTERRUPT_CPU_INT1_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT1_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT1_PRI_M  ((CORE0_INTERRUPT_CPU_INT1_PRI_V)<<(CORE0_INTERRUPT_CPU_INT1_PRI_S))
#define CORE0_INTERRUPT_CPU_INT1_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT1_PRI_S  0

#define CORE0_INTERRUPT_INT2_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x218)
/* CORE0_INTERRUPT_CPU_INT2_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT2_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT2_PRI_M  ((CORE0_INTERRUPT_CPU_INT2_PRI_V)<<(CORE0_INTERRUPT_CPU_INT2_PRI_S))
#define CORE0_INTERRUPT_CPU_INT2_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT2_PRI_S  0

#define CORE0_INTERRUPT_INT3_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x21C)
/* CORE0_INTERRUPT_CPU_INT3_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT3_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT3_PRI_M  ((CORE0_INTERRUPT_CPU_INT3_PRI_V)<<(CORE0_INTERRUPT_CPU_INT3_PRI_S))
#define CORE0_INTERRUPT_CPU_INT3_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT3_PRI_S  0

#define CORE0_INTERRUPT_INT4_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x220)
/* CORE0_INTERRUPT_CPU_INT4_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT4_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT4_PRI_M  ((CORE0_INTERRUPT_CPU_INT4_PRI_V)<<(CORE0_INTERRUPT_CPU_INT4_PRI_S))
#define CORE0_INTERRUPT_CPU_INT4_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT4_PRI_S  0

#define CORE0_INTERRUPT_INT5_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x224)
/* CORE0_INTERRUPT_CPU_INT5_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT5_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT5_PRI_M  ((CORE0_INTERRUPT_CPU_INT5_PRI_V)<<(CORE0_INTERRUPT_CPU_INT5_PRI_S))
#define CORE0_INTERRUPT_CPU_INT5_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT5_PRI_S  0

#define CORE0_INTERRUPT_INT6_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x228)
/* CORE0_INTERRUPT_CPU_INT6_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT6_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT6_PRI_M  ((CORE0_INTERRUPT_CPU_INT6_PRI_V)<<(CORE0_INTERRUPT_CPU_INT6_PRI_S))
#define CORE0_INTERRUPT_CPU_INT6_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT6_PRI_S  0

#define CORE0_INTERRUPT_INT7_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x22C)
/* CORE0_INTERRUPT_CPU_INT7_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT7_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT7_PRI_M  ((CORE0_INTERRUPT_CPU_INT7_PRI_V)<<(CORE0_INTERRUPT_CPU_INT7_PRI_S))
#define CORE0_INTERRUPT_CPU_INT7_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT7_PRI_S  0

#define CORE0_INTERRUPT_INT8_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x230)
/* CORE0_INTERRUPT_CPU_INT8_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT8_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT8_PRI_M  ((CORE0_INTERRUPT_CPU_INT8_PRI_V)<<(CORE0_INTERRUPT_CPU_INT8_PRI_S))
#define CORE0_INTERRUPT_CPU_INT8_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT8_PRI_S  0

#define CORE0_INTERRUPT_INT9_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x234)
/* CORE0_INTERRUPT_CPU_INT9_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT9_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT9_PRI_M  ((CORE0_INTERRUPT_CPU_INT9_PRI_V)<<(CORE0_INTERRUPT_CPU_INT9_PRI_S))
#define CORE0_INTERRUPT_CPU_INT9_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT9_PRI_S  0

#define CORE0_INTERRUPT_INT10_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x238)
/* CORE0_INTERRUPT_CPU_INT10_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT10_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT10_PRI_M  ((CORE0_INTERRUPT_CPU_INT10_PRI_V)<<(CORE0_INTERRUPT_CPU_INT10_PRI_S))
#define CORE0_INTERRUPT_CPU_INT10_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT10_PRI_S  0

#define CORE0_INTERRUPT_INT11_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x23C)
/* CORE0_INTERRUPT_CPU_INT11_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT11_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT11_PRI_M  ((CORE0_INTERRUPT_CPU_INT11_PRI_V)<<(CORE0_INTERRUPT_CPU_INT11_PRI_S))
#define CORE0_INTERRUPT_CPU_INT11_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT11_PRI_S  0

#define CORE0_INTERRUPT_INT12_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x240)
/* CORE0_INTERRUPT_CPU_INT12_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT12_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT12_PRI_M  ((CORE0_INTERRUPT_CPU_INT12_PRI_V)<<(CORE0_INTERRUPT_CPU_INT12_PRI_S))
#define CORE0_INTERRUPT_CPU_INT12_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT12_PRI_S  0

#define CORE0_INTERRUPT_INT13_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x244)
/* CORE0_INTERRUPT_CPU_INT13_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT13_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT13_PRI_M  ((CORE0_INTERRUPT_CPU_INT13_PRI_V)<<(CORE0_INTERRUPT_CPU_INT13_PRI_S))
#define CORE0_INTERRUPT_CPU_INT13_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT13_PRI_S  0

#define CORE0_INTERRUPT_INT14_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x248)
/* CORE0_INTERRUPT_CPU_INT14_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT14_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT14_PRI_M  ((CORE0_INTERRUPT_CPU_INT14_PRI_V)<<(CORE0_INTERRUPT_CPU_INT14_PRI_S))
#define CORE0_INTERRUPT_CPU_INT14_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT14_PRI_S  0

#define CORE0_INTERRUPT_INT15_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x24C)
/* CORE0_INTERRUPT_CPU_INT15_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT15_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT15_PRI_M  ((CORE0_INTERRUPT_CPU_INT15_PRI_V)<<(CORE0_INTERRUPT_CPU_INT15_PRI_S))
#define CORE0_INTERRUPT_CPU_INT15_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT15_PRI_S  0

#define CORE0_INTERRUPT_INT16_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x250)
/* CORE0_INTERRUPT_CPU_INT16_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT16_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT16_PRI_M  ((CORE0_INTERRUPT_CPU_INT16_PRI_V)<<(CORE0_INTERRUPT_CPU_INT16_PRI_S))
#define CORE0_INTERRUPT_CPU_INT16_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT16_PRI_S  0

#define CORE0_INTERRUPT_INT17_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x254)
/* CORE0_INTERRUPT_CPU_INT17_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT17_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT17_PRI_M  ((CORE0_INTERRUPT_CPU_INT17_PRI_V)<<(CORE0_INTERRUPT_CPU_INT17_PRI_S))
#define CORE0_INTERRUPT_CPU_INT17_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT17_PRI_S  0

#define CORE0_INTERRUPT_INT18_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x258)
/* CORE0_INTERRUPT_CPU_INT18_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT18_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT18_PRI_M  ((CORE0_INTERRUPT_CPU_INT18_PRI_V)<<(CORE0_INTERRUPT_CPU_INT18_PRI_S))
#define CORE0_INTERRUPT_CPU_INT18_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT18_PRI_S  0

#define CORE0_INTERRUPT_INT19_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x25C)
/* CORE0_INTERRUPT_CPU_INT19_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT19_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT19_PRI_M  ((CORE0_INTERRUPT_CPU_INT19_PRI_V)<<(CORE0_INTERRUPT_CPU_INT19_PRI_S))
#define CORE0_INTERRUPT_CPU_INT19_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT19_PRI_S  0

#define CORE0_INTERRUPT_INT20_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x260)
/* CORE0_INTERRUPT_CPU_INT20_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT20_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT20_PRI_M  ((CORE0_INTERRUPT_CPU_INT20_PRI_V)<<(CORE0_INTERRUPT_CPU_INT20_PRI_S))
#define CORE0_INTERRUPT_CPU_INT20_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT20_PRI_S  0

#define CORE0_INTERRUPT_INT21_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x264)
/* CORE0_INTERRUPT_CPU_INT21_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT21_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT21_PRI_M  ((CORE0_INTERRUPT_CPU_INT21_PRI_V)<<(CORE0_INTERRUPT_CPU_INT21_PRI_S))
#define CORE0_INTERRUPT_CPU_INT21_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT21_PRI_S  0

#define CORE0_INTERRUPT_INT22_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x268)
/* CORE0_INTERRUPT_CPU_INT22_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT22_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT22_PRI_M  ((CORE0_INTERRUPT_CPU_INT22_PRI_V)<<(CORE0_INTERRUPT_CPU_INT22_PRI_S))
#define CORE0_INTERRUPT_CPU_INT22_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT22_PRI_S  0

#define CORE0_INTERRUPT_INT23_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x26C)
/* CORE0_INTERRUPT_CPU_INT23_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT23_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT23_PRI_M  ((CORE0_INTERRUPT_CPU_INT23_PRI_V)<<(CORE0_INTERRUPT_CPU_INT23_PRI_S))
#define CORE0_INTERRUPT_CPU_INT23_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT23_PRI_S  0

#define CORE0_INTERRUPT_INT24_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x270)
/* CORE0_INTERRUPT_CPU_INT24_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT24_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT24_PRI_M  ((CORE0_INTERRUPT_CPU_INT24_PRI_V)<<(CORE0_INTERRUPT_CPU_INT24_PRI_S))
#define CORE0_INTERRUPT_CPU_INT24_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT24_PRI_S  0

#define CORE0_INTERRUPT_INT25_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x274)
/* CORE0_INTERRUPT_CPU_INT25_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT25_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT25_PRI_M  ((CORE0_INTERRUPT_CPU_INT25_PRI_V)<<(CORE0_INTERRUPT_CPU_INT25_PRI_S))
#define CORE0_INTERRUPT_CPU_INT25_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT25_PRI_S  0

#define CORE0_INTERRUPT_INT26_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x278)
/* CORE0_INTERRUPT_CPU_INT26_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT26_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT26_PRI_M  ((CORE0_INTERRUPT_CPU_INT26_PRI_V)<<(CORE0_INTERRUPT_CPU_INT26_PRI_S))
#define CORE0_INTERRUPT_CPU_INT26_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT26_PRI_S  0

#define CORE0_INTERRUPT_INT27_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x27C)
/* CORE0_INTERRUPT_CPU_INT27_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT27_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT27_PRI_M  ((CORE0_INTERRUPT_CPU_INT27_PRI_V)<<(CORE0_INTERRUPT_CPU_INT27_PRI_S))
#define CORE0_INTERRUPT_CPU_INT27_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT27_PRI_S  0

#define CORE0_INTERRUPT_INT28_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x280)
/* CORE0_INTERRUPT_CPU_INT28_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT28_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT28_PRI_M  ((CORE0_INTERRUPT_CPU_INT28_PRI_V)<<(CORE0_INTERRUPT_CPU_INT28_PRI_S))
#define CORE0_INTERRUPT_CPU_INT28_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT28_PRI_S  0

#define CORE0_INTERRUPT_INT29_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x284)
/* CORE0_INTERRUPT_CPU_INT29_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT29_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT29_PRI_M  ((CORE0_INTERRUPT_CPU_INT29_PRI_V)<<(CORE0_INTERRUPT_CPU_INT29_PRI_S))
#define CORE0_INTERRUPT_CPU_INT29_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT29_PRI_S  0

#define CORE0_INTERRUPT_INT30_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x288)
/* CORE0_INTERRUPT_CPU_INT30_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT30_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT30_PRI_M  ((CORE0_INTERRUPT_CPU_INT30_PRI_V)<<(CORE0_INTERRUPT_CPU_INT30_PRI_S))
#define CORE0_INTERRUPT_CPU_INT30_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT30_PRI_S  0

#define CORE0_INTERRUPT_INT31_PRI_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x28C)
/* CORE0_INTERRUPT_CPU_INT31_PRI : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT31_PRI    0x0000000F
#define CORE0_INTERRUPT_CPU_INT31_PRI_M  ((CORE0_INTERRUPT_CPU_INT31_PRI_V)<<(CORE0_INTERRUPT_CPU_INT31_PRI_S))
#define CORE0_INTERRUPT_CPU_INT31_PRI_V  0xF
#define CORE0_INTERRUPT_CPU_INT31_PRI_S  0

#define CORE0_INTERRUPT_INT_THRESH_REG          (DR_REG_CORE0_INTERRUPT_BASE + 0x290)
/* CORE0_INTERRUPT_CPU_INT_THRESH : R/W ;bitpos:[7:0] ;default: 8'd0 ; */
/*description: .*/
#define CORE0_INTERRUPT_CPU_INT_THRESH    0x000000FF
#define CORE0_INTERRUPT_CPU_INT_THRESH_M  ((CORE0_INTERRUPT_CPU_INT_THRESH_V)<<(CORE0_INTERRUPT_CPU_INT_THRESH_S))
#define CORE0_INTERRUPT_CPU_INT_THRESH_V  0xFF
#define CORE0_INTERRUPT_CPU_INT_THRESH_S  0


#ifdef __cplusplus
}
#endif



#endif /*_SOC_CORE0_INTERRUPT_REG_H_ */
