// Copyright 2017-2018 Espressif Systems (Shanghai) PTE LTD
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#ifndef _SOC_MIPI_CSI_HOST_STRUCT_H_
#define _SOC_MIPI_CSI_HOST_STRUCT_H_


#ifdef __cplusplus
extern "C" {
#endif

typedef volatile struct {
    uint32_t version;
    union {
        struct {
            uint32_t n_lanes                       :    3;
            uint32_t reserved3                     :    29;
        };
        uint32_t val;
    } n_lanes;
    union {
        struct {
            uint32_t csi2_resetn                   :    1;
            uint32_t reserved1                     :    31;
        };
        uint32_t val;
    } csi2_resetn;
    union {
        struct {
            uint32_t status_int_phy_fatal          :    1;
            uint32_t status_int_pkt_fatal          :    1;
            uint32_t status_int_bndry_frame_fatal  :    1;
            uint32_t status_int_seq_frame_fatal    :    1;
            uint32_t status_int_crc_frame_fatal    :    1;
            uint32_t status_int_pld_crc_fatal      :    1;
            uint32_t status_int_data_id            :    1;
            uint32_t status_int_ecc_corrected      :    1;
            uint32_t reserved8                     :    8;
            uint32_t status_int_phy                :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    6;
        };
        uint32_t val;
    } int_st_main;
    uint32_t reserved_10;
    uint32_t reserved_14;
    uint32_t reserved_18;
    uint32_t reserved_1c;
    uint32_t reserved_20;
    uint32_t reserved_24;
    uint32_t reserved_28;
    uint32_t reserved_2c;
    uint32_t reserved_30;
    uint32_t reserved_34;
    uint32_t reserved_38;
    uint32_t reserved_3c;
    union {
        struct {
            uint32_t phy_shutdownz                 :    1;
            uint32_t reserved1                     :    31;
        };
        uint32_t val;
    } phy_shutdownz;
    union {
        struct {
            uint32_t dphy_rstz                     :    1;
            uint32_t reserved1                     :    31;
        };
        uint32_t val;
    } dphy_rstz;
    union {
        struct {
            uint32_t phy_rxulpsesc_0               :    1;
            uint32_t phy_rxulpsesc_1               :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    8;
            uint32_t phy_rxulpsclknot              :    1;
            uint32_t phy_rxclkactivehs             :    1;
            uint32_t reserved18                    :    14;
        };
        uint32_t val;
    } phy_rx;
    union {
        struct {
            uint32_t phy_stopstatedata_0           :    1;
            uint32_t phy_stopstatedata_1           :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    8;
            uint32_t phy_stopstateclk              :    1;
            uint32_t reserved17                    :    15;
        };
        uint32_t val;
    } phy_stopstate;
    union {
        struct {
            uint32_t phy_testclr                   :    1;
            uint32_t phy_testclk                   :    1;
            uint32_t reserved2                     :    30;
        };
        uint32_t val;
    } phy_test_ctrl0;
    union {
        struct {
            uint32_t phy_testdin                   :    8;
            uint32_t phy_testdout                  :    8;
            uint32_t phy_testen                    :    1;
            uint32_t reserved17                    :    15;
        };
        uint32_t val;
    } phy_test_ctrl1;
    uint32_t reserved_58;
    uint32_t reserved_5c;
    uint32_t reserved_60;
    uint32_t reserved_64;
    uint32_t reserved_68;
    uint32_t reserved_6c;
    uint32_t reserved_70;
    uint32_t reserved_74;
    uint32_t reserved_78;
    uint32_t reserved_7c;
    uint32_t reserved_80;
    uint32_t reserved_84;
    uint32_t reserved_88;
    uint32_t reserved_8c;
    uint32_t reserved_90;
    uint32_t reserved_94;
    uint32_t reserved_98;
    uint32_t reserved_9c;
    uint32_t reserved_a0;
    uint32_t reserved_a4;
    uint32_t reserved_a8;
    uint32_t reserved_ac;
    uint32_t reserved_b0;
    uint32_t reserved_b4;
    uint32_t reserved_b8;
    uint32_t reserved_bc;
    uint32_t reserved_c0;
    uint32_t reserved_c4;
    union {
        struct {
            uint32_t vcx                           :    1;
            uint32_t reserved1                     :    31;
        };
        uint32_t val;
    } vc_extension;
    union {
        struct {
            uint32_t rxskewcalhs                   :    1;
            uint32_t reserved1                     :    31;
        };
        uint32_t val;
    } phy_cal;
    uint32_t reserved_d0;
    uint32_t reserved_d4;
    uint32_t reserved_d8;
    uint32_t reserved_dc;
    union {
        struct {
            uint32_t phy_errsotsynchs_0            :    1;
            uint32_t phy_errsotsynchs_1            :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    1;
            uint32_t reserved9                     :    7;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    13;
        };
        uint32_t val;
    } int_st_phy_fatal;
    union {
        struct {
            uint32_t mask_phy_errsotsynchs_0       :    1;
            uint32_t mask_phy_errsotsynchs_1       :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    1;
            uint32_t reserved9                     :    7;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    13;
        };
        uint32_t val;
    } int_msk_phy_fatal;
    union {
        struct {
            uint32_t force_phy_errsotsynchs_0      :    1;
            uint32_t force_phy_errsotsynchs_1      :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    1;
            uint32_t reserved9                     :    7;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    13;
        };
        uint32_t val;
    } int_force_phy_fatal;
    uint32_t reserved_ec;
    union {
        struct {
            uint32_t err_ecc_double                :    1;
            uint32_t shorter_payload               :    1;
            uint32_t reserved2                     :    30;
        };
        uint32_t val;
    } int_st_pkt_fatal;
    union {
        struct {
            uint32_t mask_err_ecc_double           :    1;
            uint32_t mask_shorter_payload          :    1;
            uint32_t reserved2                     :    30;
        };
        uint32_t val;
    } int_msk_pkt_fatal;
    union {
        struct {
            uint32_t force_err_ecc_double          :    1;
            uint32_t force_shorter_payload         :    1;
            uint32_t reserved2                     :    30;
        };
        uint32_t val;
    } int_force_pkt_fatal;
    uint32_t reserved_fc;
    uint32_t reserved_100;
    uint32_t reserved_104;
    uint32_t reserved_108;
    uint32_t reserved_10c;
    union {
        struct {
            uint32_t phy_errsoths_0                :    1;
            uint32_t phy_errsoths_1                :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    8;
            uint32_t phy_erresc_0                  :    1;
            uint32_t phy_erresc_1                  :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    8;
        };
        uint32_t val;
    } int_st_phy;
    union {
        struct {
            uint32_t mask_phy_errsoths_0           :    1;
            uint32_t mask_phy_errsoths_1           :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    8;
            uint32_t mask_phy_erresc_0             :    1;
            uint32_t mask_phy_erresc_1             :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    8;
        };
        uint32_t val;
    } int_msk_phy;
    union {
        struct {
            uint32_t force_phy_errsoths_0          :    1;
            uint32_t force_phy_errsoths_1          :    1;
            uint32_t reserved2                     :    1;
            uint32_t reserved3                     :    1;
            uint32_t reserved4                     :    1;
            uint32_t reserved5                     :    1;
            uint32_t reserved6                     :    1;
            uint32_t reserved7                     :    1;
            uint32_t reserved8                     :    8;
            uint32_t force_phy_erresc_0            :    1;
            uint32_t force_phy_erresc_1            :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    8;
        };
        uint32_t val;
    } int_force_phy;
    uint32_t reserved_11c;
    uint32_t reserved_120;
    uint32_t reserved_124;
    uint32_t reserved_128;
    uint32_t reserved_12c;
    uint32_t reserved_130;
    uint32_t reserved_134;
    uint32_t reserved_138;
    uint32_t reserved_13c;
    uint32_t reserved_140;
    uint32_t reserved_144;
    uint32_t reserved_148;
    uint32_t reserved_14c;
    uint32_t reserved_150;
    uint32_t reserved_154;
    uint32_t reserved_158;
    uint32_t reserved_15c;
    uint32_t reserved_160;
    uint32_t reserved_164;
    uint32_t reserved_168;
    uint32_t reserved_16c;
    uint32_t reserved_170;
    uint32_t reserved_174;
    uint32_t reserved_178;
    uint32_t reserved_17c;
    uint32_t reserved_180;
    uint32_t reserved_184;
    uint32_t reserved_188;
    uint32_t reserved_18c;
    uint32_t reserved_190;
    uint32_t reserved_194;
    uint32_t reserved_198;
    uint32_t reserved_19c;
    uint32_t reserved_1a0;
    uint32_t reserved_1a4;
    uint32_t reserved_1a8;
    uint32_t reserved_1ac;
    uint32_t reserved_1b0;
    uint32_t reserved_1b4;
    uint32_t reserved_1b8;
    uint32_t reserved_1bc;
    uint32_t reserved_1c0;
    uint32_t reserved_1c4;
    uint32_t reserved_1c8;
    uint32_t reserved_1cc;
    uint32_t reserved_1d0;
    uint32_t reserved_1d4;
    uint32_t reserved_1d8;
    uint32_t reserved_1dc;
    uint32_t reserved_1e0;
    uint32_t reserved_1e4;
    uint32_t reserved_1e8;
    uint32_t reserved_1ec;
    uint32_t reserved_1f0;
    uint32_t reserved_1f4;
    uint32_t reserved_1f8;
    uint32_t reserved_1fc;
    uint32_t reserved_200;
    uint32_t reserved_204;
    uint32_t reserved_208;
    uint32_t reserved_20c;
    uint32_t reserved_210;
    uint32_t reserved_214;
    uint32_t reserved_218;
    uint32_t reserved_21c;
    uint32_t reserved_220;
    uint32_t reserved_224;
    uint32_t reserved_228;
    uint32_t reserved_22c;
    uint32_t reserved_230;
    uint32_t reserved_234;
    uint32_t reserved_238;
    uint32_t reserved_23c;
    uint32_t reserved_240;
    uint32_t reserved_244;
    uint32_t reserved_248;
    uint32_t reserved_24c;
    uint32_t reserved_250;
    uint32_t reserved_254;
    uint32_t reserved_258;
    uint32_t reserved_25c;
    uint32_t reserved_260;
    uint32_t reserved_264;
    uint32_t reserved_268;
    uint32_t reserved_26c;
    uint32_t reserved_270;
    uint32_t reserved_274;
    uint32_t reserved_278;
    uint32_t reserved_27c;
    union {
        struct {
            uint32_t err_f_bndry_match_vc0         :    1;
            uint32_t err_f_bndry_match_vc1         :    1;
            uint32_t err_f_bndry_match_vc2         :    1;
            uint32_t err_f_bndry_match_vc3         :    1;
            uint32_t err_f_bndry_match_vc4         :    1;
            uint32_t err_f_bndry_match_vc5         :    1;
            uint32_t err_f_bndry_match_vc6         :    1;
            uint32_t err_f_bndry_match_vc7         :    1;
            uint32_t err_f_bndry_match_vc8         :    1;
            uint32_t err_f_bndry_match_vc9         :    1;
            uint32_t err_f_bndry_match_vc10        :    1;
            uint32_t err_f_bndry_match_vc11        :    1;
            uint32_t err_f_bndry_match_vc12        :    1;
            uint32_t err_f_bndry_match_vc13        :    1;
            uint32_t err_f_bndry_match_vc14        :    1;
            uint32_t err_f_bndry_match_vc15        :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_st_bndry_frame_fatal;
    union {
        struct {
            uint32_t err_f_bndry_match_vc0         :    1;
            uint32_t err_f_bndry_match_vc1         :    1;
            uint32_t err_f_bndry_match_vc2         :    1;
            uint32_t err_f_bndry_match_vc3         :    1;
            uint32_t err_f_bndry_match_vc4         :    1;
            uint32_t err_f_bndry_match_vc5         :    1;
            uint32_t err_f_bndry_match_vc6         :    1;
            uint32_t err_f_bndry_match_vc7         :    1;
            uint32_t err_f_bndry_match_vc8         :    1;
            uint32_t err_f_bndry_match_vc9         :    1;
            uint32_t err_f_bndry_match_vc10        :    1;
            uint32_t err_f_bndry_match_vc11        :    1;
            uint32_t err_f_bndry_match_vc12        :    1;
            uint32_t err_f_bndry_match_vc13        :    1;
            uint32_t err_f_bndry_match_vc14        :    1;
            uint32_t err_f_bndry_match_vc15        :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_msk_bndry_frame_fatal;
    union {
        struct {
            uint32_t err_f_bndry_match_vc0         :    1;
            uint32_t err_f_bndry_match_vc1         :    1;
            uint32_t err_f_bndry_match_vc2         :    1;
            uint32_t err_f_bndry_match_vc3         :    1;
            uint32_t err_f_bndry_match_vc4         :    1;
            uint32_t err_f_bndry_match_vc5         :    1;
            uint32_t err_f_bndry_match_vc6         :    1;
            uint32_t err_f_bndry_match_vc7         :    1;
            uint32_t err_f_bndry_match_vc8         :    1;
            uint32_t err_f_bndry_match_vc9         :    1;
            uint32_t err_f_bndry_match_vc10        :    1;
            uint32_t err_f_bndry_match_vc11        :    1;
            uint32_t err_f_bndry_match_vc12        :    1;
            uint32_t err_f_bndry_match_vc13        :    1;
            uint32_t err_f_bndry_match_vc14        :    1;
            uint32_t err_f_bndry_match_vc15        :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_force_bndry_frame_fatal;
    uint32_t reserved_28c;
    union {
        struct {
            uint32_t err_f_seq_vc0                 :    1;
            uint32_t err_f_seq_vc1                 :    1;
            uint32_t err_f_seq_vc2                 :    1;
            uint32_t err_f_seq_vc3                 :    1;
            uint32_t err_f_seq_vc4                 :    1;
            uint32_t err_f_seq_vc5                 :    1;
            uint32_t err_f_seq_vc6                 :    1;
            uint32_t err_f_seq_vc7                 :    1;
            uint32_t err_f_seq_vc8                 :    1;
            uint32_t err_f_seq_vc9                 :    1;
            uint32_t err_f_seq_vc10                :    1;
            uint32_t err_f_seq_vc11                :    1;
            uint32_t err_f_seq_vc12                :    1;
            uint32_t err_f_seq_vc13                :    1;
            uint32_t err_f_seq_vc14                :    1;
            uint32_t err_f_seq_vc15                :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_st_seq_frame_fatal;
    union {
        struct {
            uint32_t err_f_seq_vc0                 :    1;
            uint32_t err_f_seq_vc1                 :    1;
            uint32_t err_f_seq_vc2                 :    1;
            uint32_t err_f_seq_vc3                 :    1;
            uint32_t err_f_seq_vc4                 :    1;
            uint32_t err_f_seq_vc5                 :    1;
            uint32_t err_f_seq_vc6                 :    1;
            uint32_t err_f_seq_vc7                 :    1;
            uint32_t err_f_seq_vc8                 :    1;
            uint32_t err_f_seq_vc9                 :    1;
            uint32_t err_f_seq_vc10                :    1;
            uint32_t err_f_seq_vc11                :    1;
            uint32_t err_f_seq_vc12                :    1;
            uint32_t err_f_seq_vc13                :    1;
            uint32_t err_f_seq_vc14                :    1;
            uint32_t err_f_seq_vc15                :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_msk_seq_frame_fatal;
    union {
        struct {
            uint32_t err_f_seq_vc0                 :    1;
            uint32_t err_f_seq_vc1                 :    1;
            uint32_t err_f_seq_vc2                 :    1;
            uint32_t err_f_seq_vc3                 :    1;
            uint32_t err_f_seq_vc4                 :    1;
            uint32_t err_f_seq_vc5                 :    1;
            uint32_t err_f_seq_vc6                 :    1;
            uint32_t err_f_seq_vc7                 :    1;
            uint32_t err_f_seq_vc8                 :    1;
            uint32_t err_f_seq_vc9                 :    1;
            uint32_t err_f_seq_vc10                :    1;
            uint32_t err_f_seq_vc11                :    1;
            uint32_t err_f_seq_vc12                :    1;
            uint32_t err_f_seq_vc13                :    1;
            uint32_t err_f_seq_vc14                :    1;
            uint32_t err_f_seq_vc15                :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_force_seq_frame_fatal;
    uint32_t reserved_29c;
    union {
        struct {
            uint32_t err_frame_data_vc0            :    1;
            uint32_t err_frame_data_vc1            :    1;
            uint32_t err_frame_data_vc2            :    1;
            uint32_t err_frame_data_vc3            :    1;
            uint32_t err_frame_data_vc4            :    1;
            uint32_t err_frame_data_vc5            :    1;
            uint32_t err_frame_data_vc6            :    1;
            uint32_t err_frame_data_vc7            :    1;
            uint32_t err_frame_data_vc8            :    1;
            uint32_t err_frame_data_vc9            :    1;
            uint32_t err_frame_data_vc10           :    1;
            uint32_t err_frame_data_vc11           :    1;
            uint32_t err_frame_data_vc12           :    1;
            uint32_t err_frame_data_vc13           :    1;
            uint32_t err_frame_data_vc14           :    1;
            uint32_t err_frame_data_vc15           :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_st_crc_frame_fatal;
    union {
        struct {
            uint32_t err_frame_data_vc0            :    1;
            uint32_t err_frame_data_vc1            :    1;
            uint32_t err_frame_data_vc2            :    1;
            uint32_t err_frame_data_vc3            :    1;
            uint32_t err_frame_data_vc4            :    1;
            uint32_t err_frame_data_vc5            :    1;
            uint32_t err_frame_data_vc6            :    1;
            uint32_t err_frame_data_vc7            :    1;
            uint32_t err_frame_data_vc8            :    1;
            uint32_t err_frame_data_vc9            :    1;
            uint32_t err_frame_data_vc10           :    1;
            uint32_t err_frame_data_vc11           :    1;
            uint32_t err_frame_data_vc12           :    1;
            uint32_t err_frame_data_vc13           :    1;
            uint32_t err_frame_data_vc14           :    1;
            uint32_t err_frame_data_vc15           :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_msk_crc_frame_fatal;
    union {
        struct {
            uint32_t err_frame_data_vc0            :    1;
            uint32_t err_frame_data_vc1            :    1;
            uint32_t err_frame_data_vc2            :    1;
            uint32_t err_frame_data_vc3            :    1;
            uint32_t err_frame_data_vc4            :    1;
            uint32_t err_frame_data_vc5            :    1;
            uint32_t err_frame_data_vc6            :    1;
            uint32_t err_frame_data_vc7            :    1;
            uint32_t err_frame_data_vc8            :    1;
            uint32_t err_frame_data_vc9            :    1;
            uint32_t err_frame_data_vc10           :    1;
            uint32_t err_frame_data_vc11           :    1;
            uint32_t err_frame_data_vc12           :    1;
            uint32_t err_frame_data_vc13           :    1;
            uint32_t err_frame_data_vc14           :    1;
            uint32_t err_frame_data_vc15           :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_force_crc_frame_fatal;
    uint32_t reserved_2ac;
    union {
        struct {
            uint32_t err_crc_vc0                   :    1;
            uint32_t err_crc_vc1                   :    1;
            uint32_t err_crc_vc2                   :    1;
            uint32_t err_crc_vc3                   :    1;
            uint32_t err_crc_vc4                   :    1;
            uint32_t err_crc_vc5                   :    1;
            uint32_t err_crc_vc6                   :    1;
            uint32_t err_crc_vc7                   :    1;
            uint32_t err_crc_vc8                   :    1;
            uint32_t err_crc_vc9                   :    1;
            uint32_t err_crc_vc10                  :    1;
            uint32_t err_crc_vc11                  :    1;
            uint32_t err_crc_vc12                  :    1;
            uint32_t err_crc_vc13                  :    1;
            uint32_t err_crc_vc14                  :    1;
            uint32_t err_crc_vc15                  :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_st_pld_crc_fatal;
    union {
        struct {
            uint32_t err_crc_vc0                   :    1;
            uint32_t err_crc_vc1                   :    1;
            uint32_t err_crc_vc2                   :    1;
            uint32_t err_crc_vc3                   :    1;
            uint32_t err_crc_vc4                   :    1;
            uint32_t err_crc_vc5                   :    1;
            uint32_t err_crc_vc6                   :    1;
            uint32_t err_crc_vc7                   :    1;
            uint32_t err_crc_vc8                   :    1;
            uint32_t err_crc_vc9                   :    1;
            uint32_t err_crc_vc10                  :    1;
            uint32_t err_crc_vc11                  :    1;
            uint32_t err_crc_vc12                  :    1;
            uint32_t err_crc_vc13                  :    1;
            uint32_t err_crc_vc14                  :    1;
            uint32_t err_crc_vc15                  :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_msk_pld_crc_fatal;
    union {
        struct {
            uint32_t err_crc_vc0                   :    1;
            uint32_t err_crc_vc1                   :    1;
            uint32_t err_crc_vc2                   :    1;
            uint32_t err_crc_vc3                   :    1;
            uint32_t err_crc_vc4                   :    1;
            uint32_t err_crc_vc5                   :    1;
            uint32_t err_crc_vc6                   :    1;
            uint32_t err_crc_vc7                   :    1;
            uint32_t err_crc_vc8                   :    1;
            uint32_t err_crc_vc9                   :    1;
            uint32_t err_crc_vc10                  :    1;
            uint32_t err_crc_vc11                  :    1;
            uint32_t err_crc_vc12                  :    1;
            uint32_t err_crc_vc13                  :    1;
            uint32_t err_crc_vc14                  :    1;
            uint32_t err_crc_vc15                  :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_force_pld_crc_fatal;
    uint32_t reserved_2bc;
    union {
        struct {
            uint32_t err_id_vc0                    :    1;
            uint32_t err_id_vc1                    :    1;
            uint32_t err_id_vc2                    :    1;
            uint32_t err_id_vc3                    :    1;
            uint32_t err_id_vc4                    :    1;
            uint32_t err_id_vc5                    :    1;
            uint32_t err_id_vc6                    :    1;
            uint32_t err_id_vc7                    :    1;
            uint32_t err_id_vc8                    :    1;
            uint32_t err_id_vc9                    :    1;
            uint32_t err_id_vc10                   :    1;
            uint32_t err_id_vc11                   :    1;
            uint32_t err_id_vc12                   :    1;
            uint32_t err_id_vc13                   :    1;
            uint32_t err_id_vc14                   :    1;
            uint32_t err_id_vc15                   :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_st_data_id;
    union {
        struct {
            uint32_t err_id_vc0                    :    1;
            uint32_t err_id_vc1                    :    1;
            uint32_t err_id_vc2                    :    1;
            uint32_t err_id_vc3                    :    1;
            uint32_t err_id_vc4                    :    1;
            uint32_t err_id_vc5                    :    1;
            uint32_t err_id_vc6                    :    1;
            uint32_t err_id_vc7                    :    1;
            uint32_t err_id_vc8                    :    1;
            uint32_t err_id_vc9                    :    1;
            uint32_t err_id_vc10                   :    1;
            uint32_t err_id_vc11                   :    1;
            uint32_t err_id_vc12                   :    1;
            uint32_t err_id_vc13                   :    1;
            uint32_t err_id_vc14                   :    1;
            uint32_t err_id_vc15                   :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_msk_data_id;
    union {
        struct {
            uint32_t err_id_vc0                    :    1;
            uint32_t err_id_vc1                    :    1;
            uint32_t err_id_vc2                    :    1;
            uint32_t err_id_vc3                    :    1;
            uint32_t err_id_vc4                    :    1;
            uint32_t err_id_vc5                    :    1;
            uint32_t err_id_vc6                    :    1;
            uint32_t err_id_vc7                    :    1;
            uint32_t err_id_vc8                    :    1;
            uint32_t err_id_vc9                    :    1;
            uint32_t err_id_vc10                   :    1;
            uint32_t err_id_vc11                   :    1;
            uint32_t err_id_vc12                   :    1;
            uint32_t err_id_vc13                   :    1;
            uint32_t err_id_vc14                   :    1;
            uint32_t err_id_vc15                   :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_force_data_id;
    uint32_t reserved_2cc;
    union {
        struct {
            uint32_t err_ecc_corrected_vc0         :    1;
            uint32_t err_ecc_corrected_vc1         :    1;
            uint32_t err_ecc_corrected_vc2         :    1;
            uint32_t err_ecc_corrected_vc3         :    1;
            uint32_t err_ecc_corrected_vc4         :    1;
            uint32_t err_ecc_corrected_vc5         :    1;
            uint32_t err_ecc_corrected_vc6         :    1;
            uint32_t err_ecc_corrected_vc7         :    1;
            uint32_t err_ecc_corrected_vc8         :    1;
            uint32_t err_ecc_corrected_vc9         :    1;
            uint32_t err_ecc_corrected_vc10        :    1;
            uint32_t err_ecc_corrected_vc11        :    1;
            uint32_t err_ecc_corrected_vc12        :    1;
            uint32_t err_ecc_corrected_vc13        :    1;
            uint32_t err_ecc_corrected_vc14        :    1;
            uint32_t err_ecc_corrected_vc15        :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_st_ecc_corrected;
    union {
        struct {
            uint32_t err_ecc_corrected_vc0         :    1;
            uint32_t err_ecc_corrected_vc1         :    1;
            uint32_t err_ecc_corrected_vc2         :    1;
            uint32_t err_ecc_corrected_vc3         :    1;
            uint32_t err_ecc_corrected_vc4         :    1;
            uint32_t err_ecc_corrected_vc5         :    1;
            uint32_t err_ecc_corrected_vc6         :    1;
            uint32_t err_ecc_corrected_vc7         :    1;
            uint32_t err_ecc_corrected_vc8         :    1;
            uint32_t err_ecc_corrected_vc9         :    1;
            uint32_t err_ecc_corrected_vc10        :    1;
            uint32_t err_ecc_corrected_vc11        :    1;
            uint32_t err_ecc_corrected_vc12        :    1;
            uint32_t err_ecc_corrected_vc13        :    1;
            uint32_t err_ecc_corrected_vc14        :    1;
            uint32_t err_ecc_corrected_vc15        :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_msk_ecc_corrected;
    union {
        struct {
            uint32_t err_ecc_corrected_vc0         :    1;
            uint32_t err_ecc_corrected_vc1         :    1;
            uint32_t err_ecc_corrected_vc2         :    1;
            uint32_t err_ecc_corrected_vc3         :    1;
            uint32_t err_ecc_corrected_vc4         :    1;
            uint32_t err_ecc_corrected_vc5         :    1;
            uint32_t err_ecc_corrected_vc6         :    1;
            uint32_t err_ecc_corrected_vc7         :    1;
            uint32_t err_ecc_corrected_vc8         :    1;
            uint32_t err_ecc_corrected_vc9         :    1;
            uint32_t err_ecc_corrected_vc10        :    1;
            uint32_t err_ecc_corrected_vc11        :    1;
            uint32_t err_ecc_corrected_vc12        :    1;
            uint32_t err_ecc_corrected_vc13        :    1;
            uint32_t err_ecc_corrected_vc14        :    1;
            uint32_t err_ecc_corrected_vc15        :    1;
            uint32_t reserved16                    :    1;
            uint32_t reserved17                    :    1;
            uint32_t reserved18                    :    1;
            uint32_t reserved19                    :    1;
            uint32_t reserved20                    :    1;
            uint32_t reserved21                    :    1;
            uint32_t reserved22                    :    1;
            uint32_t reserved23                    :    1;
            uint32_t reserved24                    :    1;
            uint32_t reserved25                    :    1;
            uint32_t reserved26                    :    1;
            uint32_t reserved27                    :    1;
            uint32_t reserved28                    :    1;
            uint32_t reserved29                    :    1;
            uint32_t reserved30                    :    1;
            uint32_t reserved31                    :    1;
        };
        uint32_t val;
    } int_force_ecc_corrected;
    uint32_t reserved_2dc;
    uint32_t reserved_2e0;
    uint32_t reserved_2e4;
    uint32_t reserved_2e8;
    uint32_t reserved_2ec;
    uint32_t reserved_2f0;
    uint32_t reserved_2f4;
    uint32_t reserved_2f8;
    uint32_t reserved_2fc;
    union {
        struct {
            uint32_t scramble_enable               :    1;
            uint32_t reserved1                     :    31;
        };
        uint32_t val;
    } scrambling;
    union {
        struct {
            uint32_t scramble_seed_lane1           :    16;
            uint32_t reserved16                    :    16;
        };
        uint32_t val;
    } scrambling_seed1;
    union {
        struct {
            uint32_t scramble_seed_lane2           :    16;
            uint32_t reserved16                    :    16;
        };
        uint32_t val;
    } scrambling_seed2;
} mipi_csi_host_dev_t;
extern mipi_csi_host_dev_t MIPI_CSI_HOST;
#ifdef __cplusplus
}
#endif



#endif /*_SOC_MIPI_CSI_HOST_STRUCT_H_ */
