/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "sdkconfig.h"
#include "esp_cam_sensor_detect.h"

#if CONFIG_CAMERA_SENSOR_MOTOR_DETECT_METHOD_STATIC_STORE

#if CONFIG_CAMERA_ARDUCAM_IMX500
#include "arducam_imx500.h"
#endif
#if CONFIG_CAMERA_BF3901
#include "bf3901.h"
#endif
#if CONFIG_CAMERA_BF3925
#include "bf3925.h"
#endif
#if CONFIG_CAMERA_BF3A03
#include "bf3a03.h"
#endif
#if CONFIG_CAMERA_BF20A6
#include "bf20a6.h"
#endif
#if CONFIG_CAMERA_BF3045
#include "bf3045.h"
#endif
#if CONFIG_CAMERA_GC0308
#include "gc0308.h"
#endif
#if CONFIG_CAMERA_GC2145
#include "gc2145.h"
#endif
#if CONFIG_CAMERA_LT6911
#include "lt6911.h"
#endif
#if CONFIG_CAMERA_MIRA220
#include "mira220.h"
#endif
#if CONFIG_CAMERA_MT9D111
#include "mt9d111.h"
#endif
#if CONFIG_CAMERA_OS02N10
#include "os02n10.h"
#endif
#if CONFIG_CAMERA_OS04C10
#include "os04c10.h"
#endif
#if CONFIG_CAMERA_OV2640
#include "ov2640.h"
#endif
#if CONFIG_CAMERA_OV2710
#include "ov2710.h"
#endif
#if CONFIG_CAMERA_OV3660
#include "ov3660.h"
#endif
#if CONFIG_CAMERA_OV5640
#include "ov5640.h"
#endif
#if CONFIG_CAMERA_OV5645
#include "ov5645.h"
#endif
#if CONFIG_CAMERA_OV5647
#include "ov5647.h"
#endif
#if CONFIG_CAMERA_OV9281
#include "ov9281.h"
#endif
#if CONFIG_CAMERA_PIVARIETY
#include "pivariety.h"
#endif
#if CONFIG_CAMERA_SC030IOT
#include "sc030iot.h"
#endif
#if CONFIG_CAMERA_SC035HGS
#include "sc035hgs.h"
#endif
#if CONFIG_CAMERA_SC101IOT
#include "sc101iot.h"
#endif
#if CONFIG_CAMERA_SC121AT
#include "sc121at.h"
#endif
#if CONFIG_CAMERA_SC1346
#include "sc1346.h"
#endif
#if CONFIG_CAMERA_SC202CS
#include "sc202cs.h"
#endif
#if CONFIG_CAMERA_SC2336
#include "sc2336.h"
#endif
#if CONFIG_CAMERA_SP0A39
#include "sp0a39.h"
#endif
#if CONFIG_CAMERA_STI2250
#include "sti2250.h"
#endif

#define ESP_CAM_SENSOR_DETECT_ENTRY(f, i, j) \
    { .detect = __esp_cam_sensor_detect_fn_##f##_##i, .port = (i), .sccb_addr = (j) }

#define ESP_CAM_SENSOR_DETECT_DECLARE(f, i) \
    esp_cam_sensor_device_t *__esp_cam_sensor_detect_fn_##f##_##i(void *config)

#if CONFIG_CAMERA_ARDUCAM_IMX500_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(arducam_imx500_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_BF3901_AUTO_DETECT_SPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(bf3901_detect, ESP_CAM_SENSOR_SPI);
#endif
#if CONFIG_CAMERA_BF3925_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(bf3925_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_BF3A03_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(bf3a03_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_BF20A6_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(bf20a6_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_BF3045_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(bf3045_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_GC0308_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(gc0308_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_GC2145_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(gc2145_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_GC2145_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(gc2145_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_LT6911_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(lt6911_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_MIRA220_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(mira220_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_MT9D111_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(mt9d111_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_OS02N10_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(os02n10_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_OS04C10_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(os04c10_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_OV2640_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov2640_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_OV2710_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov2710_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_OV3660_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov3660_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_OV5640_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov5640_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_OV5640_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov5640_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_OV5645_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov5645_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_OV5647_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov5647_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_OV9281_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(ov9281_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_PIVARIETY_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(pivariety_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC030IOT_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc030iot_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_SC030IOT_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc030iot_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC035HGS_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc035hgs_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC101IOT_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc101iot_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_SC121AT_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc121at_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_SC121AT_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc121at_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC1346_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc1346_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC202CS_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc202cs_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC2336_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc2336_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif
#if CONFIG_CAMERA_SC2336_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sc2336_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_SP0A39_AUTO_DETECT_DVP_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sp0a39_detect, ESP_CAM_SENSOR_DVP);
#endif
#if CONFIG_CAMERA_SP0A39_AUTO_DETECT_SPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sp0a39_detect, ESP_CAM_SENSOR_SPI);
#endif
#if CONFIG_CAMERA_STI2250_AUTO_DETECT_MIPI_INTERFACE_SENSOR
ESP_CAM_SENSOR_DETECT_DECLARE(sti2250_detect, ESP_CAM_SENSOR_MIPI_CSI);
#endif

static const esp_cam_sensor_detect_fn_t __esp_cam_sensor_detect_fn_array_start[] = {
#if CONFIG_CAMERA_ARDUCAM_IMX500_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(arducam_imx500_detect, ESP_CAM_SENSOR_MIPI_CSI, ARDUCAM_IMX500_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_BF3901_AUTO_DETECT_SPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(bf3901_detect, ESP_CAM_SENSOR_SPI, BF3901_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_BF3925_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(bf3925_detect, ESP_CAM_SENSOR_DVP, BF3925_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_BF3A03_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(bf3a03_detect, ESP_CAM_SENSOR_DVP, BF3A03_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_BF20A6_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(bf20a6_detect, ESP_CAM_SENSOR_DVP, BF20A6_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_BF3045_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(bf3045_detect, ESP_CAM_SENSOR_DVP, BF3045_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_GC0308_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(gc0308_detect, ESP_CAM_SENSOR_DVP, GC0308_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_GC2145_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(gc2145_detect, ESP_CAM_SENSOR_MIPI_CSI, GC2145_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_GC2145_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(gc2145_detect, ESP_CAM_SENSOR_DVP, GC2145_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_LT6911_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(lt6911_detect, ESP_CAM_SENSOR_MIPI_CSI, LT6911_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_MIRA220_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(mira220_detect, ESP_CAM_SENSOR_MIPI_CSI, MIRA220_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_MT9D111_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(mt9d111_detect, ESP_CAM_SENSOR_DVP, MT9D111_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OS02N10_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(os02n10_detect, ESP_CAM_SENSOR_MIPI_CSI, OS02N10_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OS04C10_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(os04c10_detect, ESP_CAM_SENSOR_MIPI_CSI, OS04C10_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV2640_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov2640_detect, ESP_CAM_SENSOR_DVP, OV2640_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV2710_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov2710_detect, ESP_CAM_SENSOR_MIPI_CSI, OV2710_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV3660_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov3660_detect, ESP_CAM_SENSOR_DVP, OV3660_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV5640_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov5640_detect, ESP_CAM_SENSOR_MIPI_CSI, OV5640_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV5640_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov5640_detect, ESP_CAM_SENSOR_DVP, OV5640_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV5645_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov5645_detect, ESP_CAM_SENSOR_MIPI_CSI, OV5645_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV5647_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov5647_detect, ESP_CAM_SENSOR_MIPI_CSI, OV5647_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_OV9281_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(ov9281_detect, ESP_CAM_SENSOR_MIPI_CSI, OV9281_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_PIVARIETY_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(pivariety_detect, ESP_CAM_SENSOR_MIPI_CSI, PIVARIETY_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC030IOT_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc030iot_detect, ESP_CAM_SENSOR_DVP, SC030IOT_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC030IOT_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc030iot_detect, ESP_CAM_SENSOR_MIPI_CSI, SC030IOT_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC035HGS_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc035hgs_detect, ESP_CAM_SENSOR_MIPI_CSI, SC035HGS_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC101IOT_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc101iot_detect, ESP_CAM_SENSOR_DVP, SC101IOT_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC121AT_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc121at_detect, ESP_CAM_SENSOR_DVP, SC121AT_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC121AT_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc121at_detect, ESP_CAM_SENSOR_MIPI_CSI, SC121AT_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC1346_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc1346_detect, ESP_CAM_SENSOR_MIPI_CSI, SC1346_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC202CS_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc202cs_detect, ESP_CAM_SENSOR_MIPI_CSI, SC202CS_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC2336_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc2336_detect, ESP_CAM_SENSOR_MIPI_CSI, SC2336_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SC2336_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sc2336_detect, ESP_CAM_SENSOR_DVP, SC2336_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SP0A39_AUTO_DETECT_DVP_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sp0a39_detect, ESP_CAM_SENSOR_DVP, SP0A39_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_SP0A39_AUTO_DETECT_SPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sp0a39_detect, ESP_CAM_SENSOR_SPI, SP0A39_SCCB_ADDR),
#endif
#if CONFIG_CAMERA_STI2250_AUTO_DETECT_MIPI_INTERFACE_SENSOR
    ESP_CAM_SENSOR_DETECT_ENTRY(sti2250_detect, ESP_CAM_SENSOR_MIPI_CSI, STI2250_SCCB_ADDR),
#endif
};

#endif /* CONFIG_CAMERA_SENSOR_MOTOR_DETECT_METHOD_STATIC_STORE */

/**
 * @brief Get the array of camera sensor detect functions.
 *
 * @param array_start_ptr Pointer to the start of the array.
 * @param array_end_ptr Pointer to the end of the array.
 */
void esp_cam_sensor_detect_get_array(esp_cam_sensor_detect_fn_t **array_start_ptr, esp_cam_sensor_detect_fn_t **array_end_ptr)
{
#if CONFIG_CAMERA_SENSOR_MOTOR_DETECT_METHOD_STATIC_STORE
    int size = sizeof(__esp_cam_sensor_detect_fn_array_start) / sizeof(__esp_cam_sensor_detect_fn_array_start[0]);

    *array_start_ptr = (esp_cam_sensor_detect_fn_t *)__esp_cam_sensor_detect_fn_array_start;
    *array_end_ptr = (esp_cam_sensor_detect_fn_t *)(__esp_cam_sensor_detect_fn_array_start + size);
#else
    *array_start_ptr = (esp_cam_sensor_detect_fn_t *)&__esp_cam_sensor_detect_fn_array_start;
    *array_end_ptr = (esp_cam_sensor_detect_fn_t *)&__esp_cam_sensor_detect_fn_array_end;
#endif
}
