esp_video/examples/image_storage/usb_msc:
  enable:
    - if: IDF_TARGET in ["esp32p4", "esp32s3", "esp32s31"]
      reason: only support on esp32p4, esp32s3 and esp32s31
  depends_components:
    - esp_video
    - esp_cam_sensor
    - esp_sccb_intf
    