.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_examples_template: &build_examples_template
  <<: *build_template
  extends:
    - .before_script:build
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
    # By configuring this macro, you can append the compiled configuration file.
    # For example, using "sdkconf.etc=default" specifies the default sdkconfig file.
    EXAMPLE_CONFIG: "="
    IDF_BRANCH: master
  script:
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps==1.1.4
    - python tools/build_apps.py ${EXAMPLE_DIR} --config ${EXAMPLE_CONFIG} -t ${EXAMPLE_TARGET} -vv

#
# example build jobs
#

build_examples_esp32p4:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_CONFIG: "sdkconfig.ci.esp32p4.*="
    EXAMPLE_TARGET: esp32p4
    EXAMPLE_DIR: examples/video_basic

build_examples_esp32:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_CONFIG: "sdkconfig.ci.esp32.*="
    EXAMPLE_TARGET: esp32
    EXAMPLE_DIR: examples/http_web_camera

build_uvc_esp32p4:
  extends:
    - .build_examples_template
    - .rules:build:examples
  # IDF master has not integrated UVC
  allow_failure: true
  when: manual
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_CONFIG: "sdkconfig.defaults"
    EXAMPLE_TARGET: esp32p4
    EXAMPLE_DIR: examples/uvc
    IDF_BRANCH: feat/p4_sample_examples

#
# components build jobs
#

build_test:
  extends:
    - .build_examples_template
    - .rules:build:test
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_TARGET: esp32p4
    EXAMPLE_DIR: test

build_test_apps_posix_test_esp32s3:
  extends:
    - .build_examples_template
    - .rules:build:test_apps
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_TARGET: esp32s3
    EXAMPLE_DIR: test_apps/posix_test

build_test_apps_posix_test_esp32p4:
  extends:
    - .build_examples_template
    - .rules:build:test_apps
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_TARGET: esp32p4
    EXAMPLE_DIR: test_apps/posix_test

build_test_apps_pipeline_test_config_parse_test_esp32p4:
  extends:
    - .build_examples_template
    - .rules:build:test_apps
  allow_failure: true
  when: manual
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_TARGET: esp32p4
    EXAMPLE_DIR: test_apps/pipeline_test/config_parse_test

build_test_apps_pipeline_test_sim_device_test_esp32s3:
  extends:
    - .build_examples_template
    - .rules:build:test_apps
  allow_failure: true
  when: manual
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_TARGET: esp32s3
    EXAMPLE_DIR: test_apps/pipeline_test/sim_device_test